### PR TITLE
Create CONTRIBUTING.md

### LINKED ISSUE #15: Add CONTRIBUTING.md
Due to Hacktoverfest, we are having more contributors (and expect new ones to continue arriving afterwards). We could set up a couple of rules to contribute. I propose:
1. All contributors who publish a PR will be added to the Contributors section of the README. Thanks @Smollet777 
2. Looking into existing documentation and issues before attempting to propose a new feature.
3. Breaking changes are allowed but they must be discussed first. Will add a section in the Discussions tab.
4. Any type of suggestion (changing variable names, refactoring for efficiency, community stuff is greatly appreciated).
5. Feel free to add the standard rules as well. 

I know this is kind of meta, but it could benefit the project a lot and is an easy first issue

### PR DESCRIPTION
**Pull request by izhar360**
if you want me it edit it i am available this closes #15

### CODE REVIEW

**Comment by edvilme** [comment]
Hi. Thanks for the contribution. Looks great but the name does not correspond with the project, and it would be awesome if you could include the key points from #15

**Comment by izhar360** [comment]
> Hi. Thanks for the contribution. Looks great but the name does not correspond with the project, and it would be awesome if you could include the key points from #15

ops my bad!, DONE!

**Comment by edvilme** [comment]
Thanks a lot. I would just remove the last point on feel free to add anything and we are good to go for merge￼

**Comment by izhar360** [comment]
> Thanks a lot. I would just remove the last point on feel free to add anything and we are good to go for merge￼

done

**Comment by edvilme** [comment]
Awesome! I suppose you are participating in Hacktoverfest, is that right? To add the tag so that it counts in your benefit, let me know 😄

**Comment by izhar360** [comment]
Thank you mate!

**Comment by izhar360** [comment]
> Awesome! I suppose you are participating in Hacktoverfest, is that right? To add the tag so that it counts in your benefit, let me know 😄

yes you guessed right, please add it

**Comment by edvilme** [comment]
Done! Wish you luck and thanks a lot :)

**Pull request merged**
